apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: project-id
build:
  artifacts:
    #Cloud configuration
    - image: eu.gcr.io/project-id/servicename
      context: service-folder #folder where codebase is stored
      sync:
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: eu.gcr.io/project-id/servicename2
      context: service2-folder
      sync:
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {} #this  tag policy uses the tag latest of image
  #Cloud configuration
  googleCloudBuild:
    projectId: project-id
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/* #Where all the k8s for files are located at the top of project
